server:
    port: 8091

spring:
  application:
    name: pg-auth-service

  datasource:
    url: jdbc:mysql://localhost:3308/pg_auth_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: change-this-secret-key-change-this-secret-key-change-this-secret-key
  access-token-expiration: 1800000      # Access Token 만료 시간: 30분
  refresh-token-expiration: 1209600000  # Refresh Token 만료 시간: 14일
  signup-token-expiration: 1800000      # 회원가입 진행용 임시 토큰 만료 시간: 30분

kakao:
  client-id: f849747a4aceeba6d4ecdc77b40d7740
  client-secret: your-kakao-client-secret
  redirect-uri: http://localhost:8091/api/v1/auth/login/oauth2/code/kakao
