server:
  port: 8091

spring:
  application:
    name: pg-auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}
  signup-token-expiration: ${JWT_SIGNUP_TOKEN_EXPIRATION:1800000}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET:}
  redirect-uri: ${KAKAO_REDIRECT_URI:"http://localhost:5173/"}

merchant-service:
  url: ${MERCHANT_SERVICE_URL:http://localhost:8094}

internal:
  api-key: ${INTERNAL_API_KEY}
