server:
  port: 8091

spring:
  application:
    name: pg-auth-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/pg_auth_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-change-this-secret-key-change-this-secret-key}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:1209600000}
  signup-token-expiration: ${JWT_SIGNUP_TOKEN_EXPIRATION:1800000}

kakao:
  client-id: ${KAKAO_CLIENT_ID:f849747a4aceeba6d4ecdc77b40d7740}
  client-secret: ${KAKAO_CLIENT_SECRET:}
  redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8091/api/v1/auth/login/oauth2/code/kakao}

merchant-service:
  url: ${MERCHANT_SERVICE_URL:http://localhost:8094}
